spring:
  datasource:
    url: jdbc:tc:postgresql:16:///finance_test_db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  task:
    scheduling:
      enabled: false

